version: 2
jobs:
  test-run:
    working_directory: ~/sdclientapi
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install python3 python3-venv make -y
            make venv
            source .venv/bin/activate
      - run:
          name: Run linter, tests, check for known CVEs
          command: |
            source .venv/bin/activate
            make check

  test-against-latest-api:
    working_directory: ~/project
    machine:
      enabled: true
      # Because we are running Docker inside this job, we need a machine type.
      # CircleCI does not currently offer Debian machine images.
      image: ubuntu-2004:2023.07.1
    environment:
      DOCKER_API_VERSION: 1.23
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pyenv install 3.9
            pyenv global 3.9
            make venv
            source .venv/bin/activate
      - run:
          name: Download SecureDrop server code
          command: git clone https://github.com/freedomofpress/securedrop.git
      - run:
          name: Start spinning up the SecureDrop server container
          command: |
            cd securedrop
            NUM_SOURCES=5 make dev
          background: true
      - run:  # As suggested in https://discuss.circleci.com/t/prevent-race-conditions-by-waiting-for-services-with-dockerize/11215
          name: Install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz &&
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz &&
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for server to be up and for test sources to load
          command: |
            dockerize -wait tcp://127.0.0.1:8080 -timeout 30m
            sleep 300
      - run:
          name: Remove VCR cassettes and run tests against latest API
          command: |
            rm data/*.yml  # Removing VCR cassettes
            source .venv/bin/activate
            make test

workflows:
  version: 2
  securedrop_ci:
    jobs:
      - test-run
      - test-against-latest-api
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test-against-latest-api
